---
title: "EXTRACTING MOVIE (IMDB)"
author: "Nicole Duero BSIT 2-B"
date: "2024-02-06"
output:
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tinytex)
```
```{r}
library(rvest)
library(polite)
library(httr)
library(dplyr)
saltburn_url<-'https://www.imdb.com/title/tt17351924/reviews?ref_=tt_urv' #SALTBURN
session <- bow(saltburn_url,
               user_agent = "Educational")
session

for(url in saltburn_url){
  page <- read_html(url)
  
  saltburn_names<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf<-data.frame(
    Name=saltburn_names[1:25],
    Date=saltburn_dates[1:25],
    User_Rating=saltburn_ratings[1:25],
    Content=saltburn_reviews[1:25],
    Review=saltburn_reviewsw[1:25]
  )
}

saltburn_url2<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnrvrxq4oab62motb77faxcpuul5pjt6ubc7ouzfjnrcb4d23i275p2px3kvhogku35tid4c4'
session2 <- bow(saltburn_url2,
               user_agent = "Educational")
session2

for(url in saltburn_url2){
  page <- read_html(url)
  
  saltburn_names2<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates2<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings2<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews2<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw2<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf2<-data.frame(
    Name=saltburn_names2[1:25],
    Date=saltburn_dates2[1:25],
    User_Rating=saltburn_ratings2[1:25],
    Content=saltburn_reviews2[1:25],
    Review=saltburn_reviewsw2[1:25]
  )
}

saltburn_url3<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnztrdr4uajz3mpdx77la7dpww35pjt6ubc6pe4vvprlb4dztfta4ew64mpjq5d4zkld4tvao'
 
for(url in saltburn_url3){
  page <- read_html(url)
  
  saltburn_names3<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates3<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings3<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews3<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw3<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf3<-data.frame(
    Name=saltburn_names3[1:25],
    Date=saltburn_dates3[1:25],
    User_Rating=saltburn_ratings3[1:25],
    Content=saltburn_reviews3[1:25],
    Review=saltburn_reviewsw3[1:25]
  )
} 

saltburn_url4<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbwrlq46ajt3mpdr7hja7c7yul5pjt6ubc6oq2v7prnb4dzgei3zia4ibcxsk3ycjgo5fvco'
 
for(url in saltburn_url4){
  page <- read_html(url)
  
  saltburn_names4<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates4<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings4<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews4<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw4<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf4<-data.frame(
    Name=saltburn_names4[1:25],
    Date=saltburn_dates4[1:25],
    User_Rating=saltburn_ratings4[1:25],
    Content=saltburn_reviews4[1:25],
    Review=saltburn_reviewsw4[1:25]
  )
}  

saltburn_url5<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnbqrhqmqcb434nd37hia7b76w35pjt6ubc6oeyvtnjob4dtxb2zl77wgkbj2twtwx2dkoeow'

for(url in saltburn_url5){
  page <- read_html(url)
  
  saltburn_names5<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates5<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings5<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews5<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw5<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf5<-data.frame(
    Name=saltburn_names5[1:25],
    Date=saltburn_dates5[1:25],
    User_Rating=saltburn_ratings5[1:25],
    Content=saltburn_reviews5[1:25],
    Review=saltburn_reviewsw5[1:25]
  )
}  

saltburn_url6<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjyqps4yab33upd377fa3cp2v3hoq366sssou2vtpzmcr4k52m4krzo4hmop55lb2cyr6qez6y'
  
  for(url in saltburn_url6){
  page <- read_html(url)
  
  saltburn_names6<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates6<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings6<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews6<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw6<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf6<-data.frame(
    Name=saltburn_names6[1:25],
    Date=saltburn_dates6[1:25],
    User_Rating=saltburn_ratings6[1:25],
    Content=saltburn_reviews6[1:25],
    Review=saltburn_reviewsw6[1:25]
  )
  }  

saltburn_url7<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjzqlumybr52mmd36xpale7sutfoq366sssoq2v5mjncv4k425zel3hpn2ny2eadmyfgwmw55y'
  
for(url in saltburn_url7){
  page <- read_html(url)
  
  saltburn_names7<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates7<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings7<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews7<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw7<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf7<-data.frame(
    Name=saltburn_names7[1:25],
    Date=saltburn_dates7[1:25],
    User_Rating=saltburn_ratings7[1:25],
    Content=saltburn_reviews7[1:25],
    Review=saltburn_reviewsw7[1:25]
  )
}  

saltburn_url8<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjwrlum2bjy3aptb7xpatc72ul5pjt6ubc6om3fxmjcb4dv3t7z3svojobkx6uhnp2dmajlq'

for(url in saltburn_url8){
  page <- read_html(url)
  
  saltburn_names8<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates8<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings8<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews8<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw8<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf8<-data.frame(
    Name=saltburn_names8[1:25],
    Date=saltburn_dates8[1:25],
    User_Rating=saltburn_ratings8[1:25],
    Content=saltburn_reviews8[1:25], 
    Review=saltburn_reviewsw8[1:25]
  )
}  

saltburn_url9<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjvrds4wazt2iodr4platd7wud5pjt6ubc6ou2f3nrlb4dywe5aag3a3vlqczb5ppkmb7cng'

for(url in saltburn_url9){
  page <- read_html(url)
  
  saltburn_names9<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates9<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings9<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews9<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw9<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf9<-data.frame(
    Name=saltburn_names9[1:25],
    Date=saltburn_dates9[1:25],
    User_Rating=saltburn_ratings9[1:25],
    Content=saltburn_reviews9[1:25],
    Review=saltburn_reviewsw9[1:25]
  )
} 

saltburn_url10<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjnjqqps46az63iotz6hjahdpeul5pjt6ubc6oi3fvnblb4dzuxef22zunrtef6ljhyqbd3tyk'

for(url in saltburn_url10){
  page <- read_html(url)
  
  saltburn_names10<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates10<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings10<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews10<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw10<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf10<-data.frame(
    Name=saltburn_names10[1:25],
    Date=saltburn_dates10[1:25],
    User_Rating=saltburn_ratings10[1:25],
    Content=saltburn_reviews10[1:25],
    Review=saltburn_reviewsw10[1:25]
  )
} 

saltburn_url11<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmryqpqmmajy3andt7hlapep4udgoq366sssouyfxmrnd54k4x5mkj7xdxka5qrc2odjv6sfhni'

for(url in saltburn_url11){
  page <- read_html(url)
  
  saltburn_names11<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates11<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings11<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews11<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw11<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf11<-data.frame(
    Name=saltburn_names11[1:25],
    Date=saltburn_dates11[1:25],
    User_Rating=saltburn_ratings11[1:25],
    Content=saltburn_reviews11[1:25],
    Review=saltburn_reviewsw11[1:25]
  )
} 

saltburn_url12<-'https://www.imdb.com/title/tt17351924/reviews/_ajax?&paginationKey=g4w6ddbmqyzdo6ic4oxwjmrzrhq42bbs3mpt36hfb3a7ev35pjt6ubc6oq2flnblb4d4kr34jmkf2c23spfcrkgzbgly4'

for(url in saltburn_url12){
  page <- read_html(url)
  
  saltburn_names12<-page %>% html_nodes(".display-name-link") %>% html_text()
  saltburn_dates12<-page %>% html_nodes("span.review-date") %>% html_text()
  saltburn_ratings12<-page %>% html_nodes("span.rating-other-user-rating") %>% html_text()
  saltburn_reviews12<-page%>% html_nodes("a.title")%>%html_text()
  saltburn_reviewsw12<-page%>%html_nodes(".text.show-more__control")%>%html_text()
  
  saltburndf12<-data.frame(
    Name=saltburn_names12[1:25],
    Date=saltburn_dates12[1:25],
    User_Rating=saltburn_ratings12[1:25],
    Content=saltburn_reviews12[1:25],
    Review=saltburn_reviewsw12[1:25]
  )
} 

ACTIVITY2_DUERO<-rbind(saltburndf, saltburndf2, saltburndf3, saltburndf4, saltburndf5, saltburndf6, saltburndf7, saltburndf8, saltburndf9, saltburndf10, saltburndf11, saltburndf12)
ACTIVITY2_DUERO<-as.data.frame(ACTIVITY2_DUERO)
```
